/*
 * Auto-generated by QEMU Evolution Engine
 * Generation: 1, ID: 3
 * Model: TSO
 */

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>

#define MEMORY_SIZE 1024
#define NUM_ITERATIONS 200
#define NUM_CORES 2

volatile uint64_t shared_mem[MEMORY_SIZE / sizeof(uint64_t)];

typedef struct {
    uint64_t timestamp;
    uint32_t seq_id;
    uint32_t core_id;
    uint32_t type;
    uint64_t address;
    uint64_t value;
    uint32_t po_index;
} MemoryEvent;

#define MAX_EVENTS 1300
MemoryEvent events[NUM_CORES][MAX_EVENTS];
uint32_t event_count[NUM_CORES] = {0};

pthread_barrier_t barrier;

static inline uint64_t rdcycle() {
    uint64_t cycles;
    __asm__ volatile ("rdcycle %0" : "=r"(cycles));
    return cycles;
}

static inline void fence() {
#ifdef RISCV_TSO
    __asm__ volatile ("fence.tso" ::: "memory");
#else
    __asm__ volatile ("fence rw, rw" ::: "memory");
#endif
}

void record_event(uint32_t core_id, uint32_t type, uint64_t addr, uint64_t val, uint32_t po_idx) {
    if (event_count[core_id] >= MAX_EVENTS) return;
    
    MemoryEvent* e = &events[core_id][event_count[core_id]++];
    e->timestamp = rdcycle();
    e->seq_id = event_count[core_id] - 1;
    e->core_id = core_id;
    e->type = type;
    e->address = addr;
    e->value = val;
    e->po_index = po_idx;
}

void inst_write(uint32_t core_id, uint64_t offset, uint64_t value, uint32_t po_idx) {
    shared_mem[offset / sizeof(uint64_t)] = value;
    record_event(core_id, 0, (uint64_t)&shared_mem[offset / sizeof(uint64_t)], value, po_idx);
}

uint64_t inst_read(uint32_t core_id, uint64_t offset, uint32_t po_idx) {
    uint64_t value = shared_mem[offset / sizeof(uint64_t)];
    record_event(core_id, 1, (uint64_t)&shared_mem[offset / sizeof(uint64_t)], value, po_idx);
    return value;
}

void inst_fence_record(uint32_t core_id, uint32_t po_idx) {
    fence();
    record_event(core_id, 2, 0, 0, po_idx);
}

void* thread_0(void* arg) {
    uint32_t po_idx = 0;
    
    for (int iter = 0; iter < NUM_ITERATIONS; iter++) {
        pthread_barrier_wait(&barrier);
        
        inst_write(0, 0, 1, po_idx++);
        inst_fence_record(0, po_idx++);
        uint64_t r0 = inst_read(0, 64, po_idx++);
        
        pthread_barrier_wait(&barrier);
        
        if (iter == 0) {
            memset((void*)shared_mem, 0, MEMORY_SIZE);
            fence();
        }
    }
    
    return NULL;
}

void* thread_1(void* arg) {
    uint32_t po_idx = 0;
    
    for (int iter = 0; iter < NUM_ITERATIONS; iter++) {
        pthread_barrier_wait(&barrier);
        
        inst_write(1, 64, 1, po_idx++);
        inst_fence_record(1, po_idx++);
        uint64_t r1 = inst_read(1, 0, po_idx++);
        
        pthread_barrier_wait(&barrier);
    }
    
    return NULL;
}

void dump_trace() {
    printf("\n=== Memory Trace (TSO) - Sorted by Timestamp ===\n");
    printf("timestamp,seq_id,core_id,type,address,value,po_index\n");
    
    uint32_t idx[NUM_CORES] = {0};
    uint32_t total_events = 0;
    for (uint32_t core = 0; core < NUM_CORES; core++) {
        total_events += event_count[core];
    }
    
    for (uint32_t i = 0; i < total_events; i++) {
        uint64_t min_ts = UINT64_MAX;
        uint32_t min_core = 0;
        
        for (uint32_t core = 0; core < NUM_CORES; core++) {
            if (idx[core] < event_count[core] && events[core][idx[core]].timestamp < min_ts) {
                min_ts = events[core][idx[core]].timestamp;
                min_core = core;
            }
        }
        
        if (min_ts == UINT64_MAX) break;
        
        MemoryEvent* e = &events[min_core][idx[min_core]++];
        
        const char* type_str;
        switch (e->type) {
            case 0: type_str = "WRITE"; break;
            case 1: type_str = "READ"; break;
            case 2: type_str = "FENCE"; break;
            default: type_str = "UNKNOWN"; break;
        }
        
        printf("TRACE:%lu,%u,%u,%s,0x%lx,%lu,%u\n",
               e->timestamp, e->seq_id, e->core_id, type_str,
               e->address, e->value, e->po_index);
    }
    
    printf("=== End Trace ===\n");
}

int main() {
    printf("========================================\n");
    printf("RISC-V TSO Memory Model Test\n");
    printf("========================================\n");
    printf("Test: Store_Buffering_Evolved\n");
    printf("Iterations: %d\n", NUM_ITERATIONS);
    printf("========================================\n\n");
    
    memset((void*)shared_mem, 0, MEMORY_SIZE);
    pthread_barrier_init(&barrier, NULL, NUM_CORES);
    
    pthread_t threads[NUM_CORES];
    pthread_create(&threads[0], NULL, thread_0, NULL);
    pthread_create(&threads[1], NULL, thread_1, NULL);
    
    for (int i = 0; i < NUM_CORES; i++) {
        pthread_join(threads[i], NULL);
    }
    
    dump_trace();
    
    printf("\n========================================\n");
    printf("Test Statistics:\n");
    printf("========================================\n");
    printf("Core 0: %u events\n", event_count[0]);
    printf("Core 1: %u events\n", event_count[1]);
    printf("========================================\n\n");
    printf("✅ Test complete!\n");
    
    return 0;
}
