/*
 * RISC-V TSO Memory Model Test
 * Test: Message_Passing
 * Generated by mc2lib TSO extension
 */

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>

#define MEMORY_SIZE 1024
#define NUM_ITERATIONS 100
#define NUM_CORES 2

volatile uint64_t shared_mem[MEMORY_SIZE / sizeof(uint64_t)];

typedef struct {
    uint64_t timestamp;
    uint32_t seq_id;
    uint32_t core_id;
    uint32_t type;  // 0=WRITE, 1=READ, 2=FENCE
    uint64_t address;
    uint64_t value;
    uint32_t po_index;
} MemoryEvent;

#define MAX_EVENTS 1000
MemoryEvent events[NUM_CORES][MAX_EVENTS];
uint32_t event_count[NUM_CORES] = {0};

pthread_barrier_t barrier;

static inline uint64_t rdcycle() {
    uint64_t cycles;
    __asm__ volatile ("rdcycle %0" : "=r"(cycles));
    return cycles;
}

static inline void fence() {
#ifdef RISCV_TSO
    __asm__ volatile ("fence.tso" ::: "memory");
#else
    __asm__ volatile ("fence rw, rw" ::: "memory");
#endif
}

void record_event(uint32_t core_id, uint32_t type, uint64_t addr, uint64_t val, uint32_t po_idx) {
    if (event_count[core_id] >= MAX_EVENTS) return;
    
    MemoryEvent* e = &events[core_id][event_count[core_id]++];
    e->timestamp = rdcycle();
    e->seq_id = event_count[core_id] - 1;
    e->core_id = core_id;
    e->type = type;
    e->address = addr;
    e->value = val;
    e->po_index = po_idx;
}

void inst_write(uint32_t core_id, uint64_t offset, uint64_t value, uint32_t po_idx) {
    shared_mem[offset / sizeof(uint64_t)] = value;
    record_event(core_id, 0, (uint64_t)&shared_mem[offset / sizeof(uint64_t)], value, po_idx);
}

uint64_t inst_read(uint32_t core_id, uint64_t offset, uint32_t po_idx) {
    uint64_t value = shared_mem[offset / sizeof(uint64_t)];
    record_event(core_id, 1, (uint64_t)&shared_mem[offset / sizeof(uint64_t)], value, po_idx);
    return value;
}

void inst_fence_record(uint32_t core_id, uint32_t po_idx) {
    fence();
    record_event(core_id, 2, 0, 0, po_idx);
}

void* thread_0(void* arg) {
    uint32_t po_idx = 0;
    
    for (int iter = 0; iter < NUM_ITERATIONS; iter++) {
        pthread_barrier_wait(&barrier);
        
    inst_write(0, 0, 1, po_idx++);
    inst_fence_record(0, po_idx++);
    inst_write(0, 192, 1, po_idx++);
        
        pthread_barrier_wait(&barrier);
        
        if (iter == 0) {
            memset((void*)shared_mem, 0, MEMORY_SIZE);
            fence();
        }
    }
    
    return NULL;
}

void* thread_1(void* arg) {
    uint32_t po_idx = 0;
    
    for (int iter = 0; iter < NUM_ITERATIONS; iter++) {
        pthread_barrier_wait(&barrier);
        
    uint64_t r1 = inst_read(1, 192, po_idx++);
    inst_fence_record(1, po_idx++);
    uint64_t r1 = inst_read(1, 0, po_idx++);
        
        pthread_barrier_wait(&barrier);
    }
    
    return NULL;
}

void dump_trace() {
    printf("\n=== Memory Trace (TSO Model) ===\n");
    printf("timestamp,seq_id,core_id,type,address,value,po_index\n");
    
    for (uint32_t core = 0; core < NUM_CORES; core++) {
        for (uint32_t i = 0; i < event_count[core] && i < MAX_EVENTS; i++) {
            MemoryEvent* e = &events[core][i];
            
            const char* type_str;
            switch (e->type) {
                case 0: type_str = "WRITE"; break;
                case 1: type_str = "READ"; break;
                case 2: type_str = "FENCE"; break;
                default: type_str = "UNKNOWN"; break;
            }
            
            printf("TRACE:%lu,%u,%u,%s,0x%lx,%lu,%u\n",
                   e->timestamp, e->seq_id, e->core_id, type_str,
                   e->address, e->value, e->po_index);
        }
    }
    
    printf("=== End Trace ===\n");
}

int main() {
    printf("========================================\n");
    printf("RISC-V TSO Memory Model Test\n");
    printf("========================================\n");
    printf("Test: Message_Passing\n");
    printf("Iterations: %d\n", NUM_ITERATIONS);
    printf("========================================\n\n");
    
    memset((void*)shared_mem, 0, MEMORY_SIZE);
    pthread_barrier_init(&barrier, NULL, NUM_CORES);
    
    pthread_t threads[NUM_CORES];
    pthread_create(&threads[0], NULL, thread_0, NULL);
    pthread_create(&threads[1], NULL, thread_1, NULL);
    
    pthread_join(threads[0], NULL);
    pthread_join(threads[1], NULL);
    
    dump_trace();
    
    printf("\n========================================\n");
    printf("Test Statistics:\n");
    printf("========================================\n");
    for (uint32_t core = 0; core < NUM_CORES; core++) {
        printf("Core %u: %u events\n", core, event_count[core]);
    }
    printf("========================================\n");
    
    printf("\n✅ Test complete!\n");
    
    pthread_barrier_destroy(&barrier);
    
    return 0;
}
