#!/usr/bin/env python3
"""
QEMU TSO 测试迭代演化器
基于 mc2lib 遗传算法框架,针对 QEMU 优化
"""

import os
import sys
import json
import subprocess
import random
from typing import List, Dict, Tuple
from dataclasses import dataclass, asdict

@dataclass
class TestProgram:
    """测试程序个体"""
    id: int
    generation: int
    num_iterations: int
    fence_type: str  # 'fence.tso' or 'fence rw,rw'
    addresses: List[Tuple[int, int]]  # (core0_write_addr, core1_write_addr)
    fitness: float = 0.0
    violation_count: int = 0
    coverage_score: float = 0.0

class QemuEvolutionEngine:
    """QEMU TSO 演化引擎"""
    
    def __init__(self, 
                 population_size: int = 20,
                 num_generations: int = 10,
                 mutation_rate: float = 0.2,
                 crossover_rate: float = 0.7):
        self.population_size = population_size
        self.num_generations = num_generations
        self.mutation_rate = mutation_rate
        self.crossover_rate = crossover_rate
        
        self.population: List[TestProgram] = []
        self.generation = 0
        self.best_individual = None
        self.history = []
        
        # 工作目录
        self.work_dir = "evolution_workspace"
        os.makedirs(self.work_dir, exist_ok=True)
    
    def initialize_population(self):
        """初始化种群"""
        print(f"🧬 初始化种群 (大小: {self.population_size})")
        
        for i in range(self.population_size):
            # 随机生成测试配置
            num_iters = random.choice([50, 100, 200, 500])
            fence_type = random.choice(['fence.tso', 'fence rw,rw'])
            
            # 地址对: 简单起见,只用两个地址
            addr1 = random.choice([0, 64, 128, 256])
            addr2 = random.choice([0, 64, 128, 256])
            while addr2 == addr1:
                addr2 = random.choice([0, 64, 128, 256])
            
            individual = TestProgram(
                id=i,
                generation=0,
                num_iterations=num_iters,
                fence_type=fence_type,
                addresses=[(addr1, addr2)]
            )
            
            self.population.append(individual)
        
        print(f"✅ 种群初始化完成")
    
    def generate_c_code(self, individual: TestProgram, model: str = 'tso') -> str:
        """生成 C 代码"""
        addr1, addr2 = individual.addresses[0]
        
        fence_directive = '-DRISCV_TSO' if individual.fence_type == 'fence.tso' else ''
        fence_asm = 'fence.tso' if individual.fence_type == 'fence.tso' else 'fence rw, rw'
        
        code = f'''/*
 * Auto-generated by QEMU Evolution Engine
 * Generation: {individual.generation}, ID: {individual.id}
 * Model: {model.upper()}
 */

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>

#define MEMORY_SIZE 1024
#define NUM_ITERATIONS {individual.num_iterations}
#define NUM_CORES 2

volatile uint64_t shared_mem[MEMORY_SIZE / sizeof(uint64_t)];

typedef struct {{
    uint64_t timestamp;
    uint32_t seq_id;
    uint32_t core_id;
    uint32_t type;
    uint64_t address;
    uint64_t value;
    uint32_t po_index;
}} MemoryEvent;

#define MAX_EVENTS {individual.num_iterations * 3 * 2 + 100}
MemoryEvent events[NUM_CORES][MAX_EVENTS];
uint32_t event_count[NUM_CORES] = {{0}};

pthread_barrier_t barrier;

static inline uint64_t rdcycle() {{
    uint64_t cycles;
    __asm__ volatile ("rdcycle %0" : "=r"(cycles));
    return cycles;
}}

static inline void fence() {{
#ifdef RISCV_TSO
    __asm__ volatile ("{fence_asm}" ::: "memory");
#else
    __asm__ volatile ("fence rw, rw" ::: "memory");
#endif
}}

void record_event(uint32_t core_id, uint32_t type, uint64_t addr, uint64_t val, uint32_t po_idx) {{
    if (event_count[core_id] >= MAX_EVENTS) return;
    
    MemoryEvent* e = &events[core_id][event_count[core_id]++];
    e->timestamp = rdcycle();
    e->seq_id = event_count[core_id] - 1;
    e->core_id = core_id;
    e->type = type;
    e->address = addr;
    e->value = val;
    e->po_index = po_idx;
}}

void inst_write(uint32_t core_id, uint64_t offset, uint64_t value, uint32_t po_idx) {{
    shared_mem[offset / sizeof(uint64_t)] = value;
    record_event(core_id, 0, (uint64_t)&shared_mem[offset / sizeof(uint64_t)], value, po_idx);
}}

uint64_t inst_read(uint32_t core_id, uint64_t offset, uint32_t po_idx) {{
    uint64_t value = shared_mem[offset / sizeof(uint64_t)];
    record_event(core_id, 1, (uint64_t)&shared_mem[offset / sizeof(uint64_t)], value, po_idx);
    return value;
}}

void inst_fence_record(uint32_t core_id, uint32_t po_idx) {{
    fence();
    record_event(core_id, 2, 0, 0, po_idx);
}}

void* thread_0(void* arg) {{
    uint32_t po_idx = 0;
    
    for (int iter = 0; iter < NUM_ITERATIONS; iter++) {{
        pthread_barrier_wait(&barrier);
        
        inst_write(0, {addr1}, 1, po_idx++);
        inst_fence_record(0, po_idx++);
        uint64_t r0 = inst_read(0, {addr2}, po_idx++);
        
        pthread_barrier_wait(&barrier);
        
        if (iter == 0) {{
            memset((void*)shared_mem, 0, MEMORY_SIZE);
            fence();
        }}
    }}
    
    return NULL;
}}

void* thread_1(void* arg) {{
    uint32_t po_idx = 0;
    
    for (int iter = 0; iter < NUM_ITERATIONS; iter++) {{
        pthread_barrier_wait(&barrier);
        
        inst_write(1, {addr2}, 1, po_idx++);
        inst_fence_record(1, po_idx++);
        uint64_t r1 = inst_read(1, {addr1}, po_idx++);
        
        pthread_barrier_wait(&barrier);
    }}
    
    return NULL;
}}

void dump_trace() {{
    printf("\\n=== Memory Trace ({model.upper()}) - Sorted by Timestamp ===\\n");
    printf("timestamp,seq_id,core_id,type,address,value,po_index\\n");
    
    uint32_t idx[NUM_CORES] = {{0}};
    uint32_t total_events = 0;
    for (uint32_t core = 0; core < NUM_CORES; core++) {{
        total_events += event_count[core];
    }}
    
    for (uint32_t i = 0; i < total_events; i++) {{
        uint64_t min_ts = UINT64_MAX;
        uint32_t min_core = 0;
        
        for (uint32_t core = 0; core < NUM_CORES; core++) {{
            if (idx[core] < event_count[core] && events[core][idx[core]].timestamp < min_ts) {{
                min_ts = events[core][idx[core]].timestamp;
                min_core = core;
            }}
        }}
        
        if (min_ts == UINT64_MAX) break;
        
        MemoryEvent* e = &events[min_core][idx[min_core]++];
        
        const char* type_str;
        switch (e->type) {{
            case 0: type_str = "WRITE"; break;
            case 1: type_str = "READ"; break;
            case 2: type_str = "FENCE"; break;
            default: type_str = "UNKNOWN"; break;
        }}
        
        printf("TRACE:%lu,%u,%u,%s,0x%lx,%lu,%u\\n",
               e->timestamp, e->seq_id, e->core_id, type_str,
               e->address, e->value, e->po_index);
    }}
    
    printf("=== End Trace ===\\n");
}}

int main() {{
    printf("========================================\\n");
    printf("RISC-V {model.upper()} Memory Model Test\\n");
    printf("========================================\\n");
    printf("Test: Store_Buffering_Evolved\\n");
    printf("Iterations: %d\\n", NUM_ITERATIONS);
    printf("========================================\\n\\n");
    
    memset((void*)shared_mem, 0, MEMORY_SIZE);
    pthread_barrier_init(&barrier, NULL, NUM_CORES);
    
    pthread_t threads[NUM_CORES];
    pthread_create(&threads[0], NULL, thread_0, NULL);
    pthread_create(&threads[1], NULL, thread_1, NULL);
    
    for (int i = 0; i < NUM_CORES; i++) {{
        pthread_join(threads[i], NULL);
    }}
    
    dump_trace();
    
    printf("\\n========================================\\n");
    printf("Test Statistics:\\n");
    printf("========================================\\n");
    printf("Core 0: %u events\\n", event_count[0]);
    printf("Core 1: %u events\\n", event_count[1]);
    printf("========================================\\n\\n");
    printf("✅ Test complete!\\n");
    
    return 0;
}}
'''
        return code
    
    def compile_and_run(self, individual: TestProgram) -> Dict:
        """编译并运行测试"""
        src_file = f"{self.work_dir}/test_gen{individual.generation}_id{individual.id}.c"
        bin_file = f"{self.work_dir}/test_gen{individual.generation}_id{individual.id}"
        trace_file = f"{self.work_dir}/trace_gen{individual.generation}_id{individual.id}.txt"
        
        # 生成代码
        code = self.generate_c_code(individual, model='tso')
        with open(src_file, 'w') as f:
            f.write(code)
        
        # 编译
        march = 'rv64gc_ztso' if individual.fence_type == 'fence.tso' else 'rv64gc'
        define = '-DRISCV_TSO' if individual.fence_type == 'fence.tso' else ''
        
        compile_cmd = f"riscv64-linux-gnu-gcc -march={march} {define} -static -o {bin_file} {src_file}"
        result = subprocess.run(compile_cmd, shell=True, capture_output=True)
        
        if result.returncode != 0:
            return {'success': False, 'error': 'compilation_failed'}
        
        # 运行
        run_cmd = f"qemu-riscv64 {bin_file}"
        result = subprocess.run(run_cmd, shell=True, capture_output=True, text=True, timeout=30)
        
        if result.returncode != 0:
            return {'success': False, 'error': 'execution_failed'}
        
        # 保存 trace
        with open(trace_file, 'w') as f:
            f.write(result.stdout)
        
        # 分析结果
        from qemu_tso_verifier import TraceAnalyzer
        analyzer = TraceAnalyzer(trace_file)
        report = analyzer.generate_report(f"Gen{individual.generation}_ID{individual.id}")
        
        return {
            'success': True,
            'trace_file': trace_file,
            'report': report
        }
    
    def evaluate_fitness(self, individual: TestProgram) -> float:
        """评估适应度"""
        result = self.compile_and_run(individual)
        
        if not result['success']:
            return 0.0
        
        report = result['report']
        metrics = report['metrics']
        violations = report['violation_count']
        
        # 适应度计算
        # 目标: 更多地址覆盖 + 发现违例(对于 RVWMO)
        coverage_score = metrics['address_pairs'] * 10 + metrics['unique_addresses'] * 5
        violation_bonus = violations * 50  # 发现违例给高奖励
        
        fitness = coverage_score + violation_bonus
        
        individual.fitness = fitness
        individual.violation_count = violations
        individual.coverage_score = coverage_score
        
        return fitness
    
    def select_parents(self) -> List[TestProgram]:
        """选择父代 (锦标赛选择)"""
        tournament_size = 3
        parents = []
        
        for _ in range(2):
            tournament = random.sample(self.population, tournament_size)
            winner = max(tournament, key=lambda ind: ind.fitness)
            parents.append(winner)
        
        return parents
    
    def crossover(self, parent1: TestProgram, parent2: TestProgram) -> TestProgram:
        """交叉"""
        if random.random() > self.crossover_rate:
            return parent1
        
        # 混合配置
        child = TestProgram(
            id=len(self.population),
            generation=self.generation + 1,
            num_iterations=random.choice([parent1.num_iterations, parent2.num_iterations]),
            fence_type=random.choice([parent1.fence_type, parent2.fence_type]),
            addresses=random.choice([parent1.addresses, parent2.addresses])
        )
        
        return child
    
    def mutate(self, individual: TestProgram):
        """变异"""
        if random.random() < self.mutation_rate:
            mutation_type = random.choice(['iterations', 'fence', 'addresses'])
            
            if mutation_type == 'iterations':
                individual.num_iterations = random.choice([50, 100, 200, 500, 1000])
            elif mutation_type == 'fence':
                individual.fence_type = 'fence.tso' if individual.fence_type == 'fence rw,rw' else 'fence rw,rw'
            elif mutation_type == 'addresses':
                addr1 = random.choice([0, 64, 128, 256, 512])
                addr2 = random.choice([0, 64, 128, 256, 512])
                while addr2 == addr1:
                    addr2 = random.choice([0, 64, 128, 256, 512])
                individual.addresses = [(addr1, addr2)]
    
    def evolve(self):
        """演化主循环"""
        print(f"\n🧬 开始演化 ({self.num_generations} 代)")
        
        # 初始化
        self.initialize_population()
        
        for gen in range(self.num_generations):
            self.generation = gen
            print(f"\n{'='*60}")
            print(f"🔬 第 {gen + 1}/{self.num_generations} 代")
            print(f"{'='*60}")
            
            # 评估适应度
            print("📊 评估适应度...")
            for i, individual in enumerate(self.population):
                fitness = self.evaluate_fitness(individual)
                print(f"  [{i+1}/{len(self.population)}] ID{individual.id}: fitness={fitness:.2f}, violations={individual.violation_count}")
            
            # 记录最佳个体
            best = max(self.population, key=lambda ind: ind.fitness)
            if self.best_individual is None or best.fitness > self.best_individual.fitness:
                self.best_individual = best
            
            print(f"\n🏆 最佳个体: ID{best.id}, fitness={best.fitness:.2f}, violations={best.violation_count}")
            
            # 记录历史
            self.history.append({
                'generation': gen,
                'best_fitness': best.fitness,
                'avg_fitness': sum(ind.fitness for ind in self.population) / len(self.population),
                'best_violations': best.violation_count,
            })
            
            # 生成下一代
            if gen < self.num_generations - 1:
                print("🧬 生成下一代...")
                new_population = []
                
                # 精英保留
                elite_size = 2
                elites = sorted(self.population, key=lambda ind: ind.fitness, reverse=True)[:elite_size]
                new_population.extend(elites)
                
                # 交叉和变异
                while len(new_population) < self.population_size:
                    parents = self.select_parents()
                    child = self.crossover(parents[0], parents[1])
                    self.mutate(child)
                    new_population.append(child)
                
                self.population = new_population
        
        # 保存结果
        self.save_results()
    
    def save_results(self):
        """保存演化结果"""
        results = {
            'generations': self.num_generations,
            'population_size': self.population_size,
            'best_individual': asdict(self.best_individual) if self.best_individual else None,
            'history': self.history,
        }
        
        with open(f'{self.work_dir}/evolution_results.json', 'w') as f:
            json.dump(results, f, indent=2)
        
        print(f"\n💾 演化结果已保存到 {self.work_dir}/evolution_results.json")
        
        # 打印摘要
        print(f"\n{'='*60}")
        print(f"📊 演化摘要")
        print(f"{'='*60}")
        print(f"总代数: {self.num_generations}")
        print(f"种群大小: {self.population_size}")
        if self.best_individual:
            print(f"\n🏆 最佳个体:")
            print(f"  Generation: {self.best_individual.generation}")
            print(f"  ID: {self.best_individual.id}")
            print(f"  Fitness: {self.best_individual.fitness:.2f}")
            print(f"  Violations: {self.best_individual.violation_count}")
            print(f"  Iterations: {self.best_individual.num_iterations}")
            print(f"  Fence: {self.best_individual.fence_type}")
            print(f"  Addresses: {self.best_individual.addresses}")

if __name__ == '__main__':
    import argparse
    
    parser = argparse.ArgumentParser(description='QEMU TSO 测试迭代演化器')
    parser.add_argument('--population', type=int, default=10, help='种群大小')
    parser.add_argument('--generations', type=int, default=5, help='演化代数')
    parser.add_argument('--mutation-rate', type=float, default=0.2, help='变异率')
    parser.add_argument('--crossover-rate', type=float, default=0.7, help='交叉率')
    
    args = parser.parse_args()
    
    engine = QemuEvolutionEngine(
        population_size=args.population,
        num_generations=args.generations,
        mutation_rate=args.mutation_rate,
        crossover_rate=args.crossover_rate
    )
    
    engine.evolve()
